### ISSUE TITLE
Turso api create database under an organization

### ISSUE THREAD

**Issue by jrizo0** [ethanniser/the-beth-stack#14]
I think that right now we have to create databases under an organization.
In the API wrapper, in the `create` method, the path is `/v1/databases`, but that doesn't exist, the path is `/v1/organizations/:org_slug/databases`

**Comment by ethanniser** [comment]
it does exist its just not on the website for some reason: https://gist.github.com/athoscouto/5c524a707ae90bf72b5a6d632ca39e3b#databases-api-changes

either way you have to pass an organization (which for most people is just their personal account name)

**Comment by jrizo0** [comment]
oh ok, thanks. btw great work on the BETH Stack
