### ISSUE TITLE
create-beth-app error

### ISSUE THREAD

**Issue by darrylmorley** [ethanniser/the-beth-stack#15]
I'm trying to start a new project using the create-beth-app CLI. When I  use `bunx create-beth-app@latest` I get an error as below, this error also occurs when providing a name for the project, such as `bunx create-beth-app@latest myproject` :

```
fatal: destination path '.' already exists and is not an empty directory.
error: undefined
```

I installed bun using npm & I'm using WSL2.

**Comment by ethanniser** [comment]
The cli is extremely basic, it just does git clone .

So try making the directory first the then run command inside it

**Comment by darrylmorley** [comment]
> The cli is extremely basic, it just does git clone .
> 
> So try making the directory first the then run command inside it

That works 👍
