### ISSUE TITLE
Cannot find package "commander"

### ISSUE THREAD

**Issue by mohamed-abd-elkahlk** [ethanniser/the-beth-stack#17]
i got that error when i try  `bunx create-beth-app@latest beth`

error: Cannot find package "commander" from "/tmp/create-beth-app@latest--bunx/node_modules/create-beth-app/src/commander.ts"

**Comment by ethanniser** [comment]
totally on me, fixing now

**Comment by ethanniser** [comment]
should be fixed with 0.0.8

**Comment by mohamed-abd-elkahlk** [comment]
i go to that directory `/tmp/create-beth-app@latest--bunx` and install some package manually

**Comment by mohamed-abd-elkahlk** [comment]
> should be fixed with 0.0.8
Thank you for your help.

**Comment by mohamed-abd-elkahlk** [comment]
it's work and when it finish it gave me that 
matrix@theOne:~/websites/bun$ bunx create-beth-app@0.0.8 --project-name beth

Starting...
Running Pre-checks...
Creating new beth-stack site at ./beth
`undefined` is that a problem 

and i think  i watch your vid right now :100:
