### ISSUE TITLE
error: Could not resolve: "react". Maybe you need to "bun install"?

### ISSUE THREAD

**Issue by FMGordillo** [ethanniser/the-beth-stack#5]
I don't know if this is replicable, but I tried doing in a parallel project, and cloning your repository, and this happened:

```
code/beth_stack [main●] » bun run src/index.tsx 

error: Could not resolve: "react". Maybe you need to "bun install"?
import { Elysia, t } from "elysia";
^
code/beth_stack/src/index.tsx:1:1 
```

Is there any way to get around this?

```
bun: 0.6.2
node: 18.17.1
os: linux
```

**Comment by ethanniser** [comment]
Make sure your tsconfig JSX settings are aligned with the ones shown in the typed-html docs
