### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by TAnas0** [ethanniser/the-beth-stack#9]
First, nice app, enjoyed it as my introduction to the BETH stack, as well as your video.

Second, just starting a discussion about a vulnerability on the app: when inputing a JS script (e.g. `<script>alert(1)</script>) it gets executed. Is there some remediation to that? How is it done on the BETH stack?

**Comment by ethanniser** [comment]
Yes I am aware this is an issue. It is an actively being addressed, check out the updates to @elysia/html.

I'm working on a follow up to the original video with the updated tech, so I will leave this open till then.

**Comment by arjunindia** [comment]
You can use the `safe` attribute on elements so that the children does not render the HTML in @elysia/html I believe

**Comment by dody2004** [comment]
thanks

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>9UBr2j

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>v6i4rq

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>QNKKHm

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>HNMb9p

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Java8w

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Yll25G

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3n2m7q

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>k7yOXA

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>PRwo3w

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uufFXi

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dEpzmd

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>RbOhxx

**Comment by dody2004** [comment]
'"><div rNnTRbt=roann>jAjtMX

**Comment by dody2004** [comment]
'"></script><div rNnTRbt=roann>XLBpKh

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>FAMFec

**Comment by dody2004** [comment]
'" rNnTRbt="roannATTR" x=ykFUqr7

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bzjqmd

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>RZFTuh

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TKdL44

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>5oZ4a3

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>rtPIQw

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>QjpDhg

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tkLKhX

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>aATrjD

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>cvtotu

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1YE0Oc

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tCuC1D

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>AJTphC

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GEqN4q

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Yy44tn

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SwI04v

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dYSJE1

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>VVmpvR

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>eAn0gy

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dc0Ka4

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Npwsuv

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>VE0T02

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>yxsU4A

**Comment by dody2004** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>etf6lP

**Comment by ethanniser** [comment]
this is addressed by the `safe` attribute
[also check out the kitajs tsplugin](https://github.com/kitajs/html#sanitization)

idk why this issue got spammed as well very weird
